In [1]:
import scipy
from scipy import ndimage

import numpy as np

import warnings
warnings.filterwarnings("ignore")

In [2]:
three =  scipy.ndimage.imread('3.png', flatten=True)

In [3]:
print(three)

[[0.413 0.413 0.413 ... 0.413 0.413 0.413]
 [0.413 0.413 0.413 ... 0.413 0.413 0.413]
 [0.413 0.413 0.413 ... 1.413 0.413 0.413]
 ...
 [0.413 0.413 0.413 ... 7.    0.    0.413]
 [0.413 0.413 0.527 ... 0.    0.413 0.413]
 [0.413 0.413 0.413 ... 1.826 0.413 0.413]]


In [4]:
print(three.shape)

(171, 172)


좀 더 직관적으로 보기 위해서

In [5]:
a = three.shape[0]
b= three.shape[1]

In [6]:
#사이즈를 조정하고,
three_resize = scipy.misc.imresize(three, (int(a/10),int(b/10)), interp='bilinear', mode=None)

#255 기준으로 맞춰주고
three_resize = 1.0 - three_resize/255.0

#소수점 자리 정렬
three_resize = np.around(three_resize, decimals=1)

In [7]:
print(three_resize)

[[0.9 0.9 0.9 0.9 0.9 0.9 0.9 0.9 0.9 0.9 0.9 0.9 0.9 0.9 0.9 0.9 0.9]
 [0.9 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.9]
 [0.9 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.9]
 [0.9 1.  0.9 0.7 0.6 0.5 0.6 0.6 0.6 0.8 0.9 1.  1.  1.  1.  1.  0.9]
 [0.9 1.  0.5 0.1 0.1 0.2 0.2 0.2 0.2 0.2 0.4 0.9 1.  1.  1.  1.  0.9]
 [0.9 1.  0.8 0.7 0.7 0.8 0.8 0.9 0.7 0.2 0.2 0.8 1.  1.  1.  1.  0.9]
 [0.9 1.  1.  1.  1.  1.  1.  0.8 0.4 0.1 0.6 1.  1.  1.  1.  1.  0.9]
 [0.9 1.  1.  1.  1.  1.  0.8 0.3 0.  0.2 0.8 1.  1.  1.  1.  1.  0.9]
 [0.9 1.  1.  1.  1.  1.  0.6 0.1 0.  0.1 0.2 0.5 0.8 1.  1.  1.  0.9]
 [0.9 1.  1.  1.  1.  1.  0.9 0.8 0.6 0.4 0.1 0.  0.3 0.8 1.  1.  0.9]
 [0.9 1.  1.  1.  1.  1.  1.  1.  1.  0.9 0.6 0.1 0.1 0.6 1.  1.  0.9]
 [0.9 1.  1.  1.  1.  0.8 0.9 1.  1.  1.  0.8 0.2 0.1 0.7 1.  1.  0.9]
 [0.9 1.  1.  1.  0.8 0.3 0.7 1.  1.  0.8 0.4 0.  0.3 0.9 1.  1.  0.9]
 [0.9 1.  1.  1.  0.8 0.2 0.2 0.4 0.4 0.2 0.1 0.2 0.7 1.  1.  1.  0.9]
 [0.9 

In [8]:
abc =  scipy.ndimage.imread('abc.jpg', flatten=True)
print(abc.shape)

(1720, 2584)


In [9]:
a = abc.shape[0]
b= abc.shape[1]

#사이즈를 조정하고,
abc_resize = scipy.misc.imresize(abc, (int(a/68),int(b/137)), interp='bilinear', mode=None)

#255 기준으로 맞춰주고
abc_resize = 1.0 - abc_resize/255.0

#소수점 자리 정렬
abc_resize = np.around(abc_resize, decimals=1)

In [10]:
print(abc_resize)

[[0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.1 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.1 0.5 0.1 0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.1 0.6 0.2 0.  0.  0.  0.2 0.1 0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.1 0.7 0.5 0.1 0.  0.1 0.5 0.2 0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.1 0.6 0.5 0.4 0.3 0.4 0.6 0.1 0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.1 0.6 0.5 0.7 0.6 0.5 0.5 0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.1 0.6 0.7 0.8 0.6 0.6 0.4 0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.1 0.6 0.7 0.7 0.5 0.7 0.3 0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.1

In [11]:
##만약에, 전체 매트릭스가 안나온다면 아래 코드를 시행 후 재시도
#import sys
#import numpy
#numpy.set_printoptions(threshold=sys.maxsize)